version: '3'
services:
  postgres:
    image: postgres:15
    shm_size: 2g
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      TZ: America/Sao_Paulo
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    ports:
      - 54322:5432
